stack:
  logger:
    name: slogrus
    level: trace
    persistence:
      enable: true
      max-file-size: 10
      max-backup-size: 500
      max-backup-keep-days: 1
      dir: /tmp/logs
      backup-dir: /tmp/logs/backup
    slogrus:
      without-key: true
      without-quote: true
      timestamp-format: 2020-01-02 21:33:33.999